
// Objective-C API for talking to the following Go packages
//
//	github.com/nathanborror/Heat/Ollama
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Ollama_FRAMEWORK_H__
#define __Ollama_FRAMEWORK_H__

#include "Ollama.objc.h"
#include "Universe.objc.h"

#endif
