// Objective-C API for talking to github.com/nathanborror/Heat/Ollama Go package.
//   gobind -lang=objc github.com/nathanborror/Heat/Ollama
//
// File is generated by gobind. Do not edit.

#ifndef __Ollama_H__
#define __Ollama_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * Get makes an HTTP(S) GET request to url,
returning the resulting content or an error.
 */
FOUNDATION_EXPORT NSData* _Nullable OllamaGet(NSString* _Nullable url, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void OllamaRunServer(void);

/**
 * Version returns the version string for this package.
 */
FOUNDATION_EXPORT NSString* _Nonnull OllamaVersion(void);

#endif
